# -- Main Menu --

[[main]]
  name = "Home"
  url = "/"
  weight = 5

[[main]]
  name = "Paper"
  url = "/replication_materials/30_paper/native_representation.pdf"
  weight = 10

[[main]]
  name = "Maps"
  pageRef = "maps"
  weight = 20

[[main]]
  name = "Replication Materials"
  url = "https://github.com/nickeubank/native_american_dislocation_site/replication_materials"
  weight = 30
