# -- Main Menu --

[[main]]
  name = "Figures"
  pageRef = "figures"
  weight = 10

[[main]]
  name = "Probability Plots"
  pageRef = "figures/probability-plots"
  weight = 20

[[main]]
  name = "District Native Share"
  pageRef = "figures/district-native-share"
  weight = 30

[[main]]
  name = "Dislocation Maps"
  pageRef = "figures/dislocation-maps"
  weight = 40

[[main]]
  name = "Proportional Dislocation"
  pageRef = "figures/proportional-dislocation-maps"
  weight = 50
